services:
  postgres:
    image: postgis/postgis:16-master
    container_name: petradar-db
    ports:
      - 5678:5432
    environment:
      - POSTGRES_PASSWORD=JosaAguirre..10
      - POSTGRES_DB=petradar
      - POSTGRES_USER=postgres
    volumes:
      - petradar_data:/var/lib/postgresql
  
  redis:
    image: redis
    container_name: pet-radar-redis
    ports:
      - 6379:6379
    volumes:
      - redis_db:/data

volumes:
  petradar_data:
  redis_db: